trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: ivy
    name: 3rwww1/ivy
    ref: test/azure-artifact-behaves-like-a-2000s-web-app
    type: github
    endpoint: 3rwww1
  - repository: sbt
    name: sbt/sbt
    ref: develop
    type: github
    endpoint: 3rwww1

steps:
# checkout and build Ivy with user agent overriden
- checkout: ivy
  path: ivy
  displayName: 'checkout Ivy'


# checkout and build sbt develop branch
- checkout: sbt
  path: sbt
  displayName: 'checkout SBT'

# checkout and try publishing sample
- checkout: self
  path: project
  displayName: 'checkout publishing sample'

- script: cat logging.properties
  workingDirectory: $(Agent.BuildDirectory)/project

- script: sbt publishLocal -Dsbt.ci=true
  workingDirectory: $(Agent.BuildDirectory)/ivy
  displayName: 'build Ivy'

- script: sbt publishLocal -Dsbt.ci=true
  workingDirectory: $(Agent.BuildDirectory)/sbt
  displayName: 'build SBT 1.4.0-SNAPSHOT'

- script: sbt publish -Dsbt.ci=true -Djava.util.logging.config.file=./logging.properties
  env:
    AZURE_PAT: $(azurePat)
  workingDirectory: $(Agent.BuildDirectory)/project
  displayName: 'try to publish sample to azure artifacts and fail because of bad user agent string...'

  # Try to publish sample to azure artifacts, this time telling azure artifact we are Maven/3.6.3 and not Ivy/someversion'
  # See it work almost automagically :)
- script: |
    cp ${HOME}/.ivy2/local/org.scala-sbt.ivy/ivy/2.3.0-sbt-c5ec05f44277f889393974973277245226516abe/jars/ivy.jar \
    ${HOME}/.sbt/boot/scala-2.12.11/org.scala-sbt/sbt/1.4.0-SNAPSHOT/ivy-2.3.0-sbt-fa726854dd30be842ff9e6d2093df6adfe3871f5.jar
  workingDirectory: $(Agent.BuildDirectory)/ivy
  condition: or(failed(), succeeded())
  displayName: 'override Ivy lib with one that overrides its UA string'

- script: sbt publish -Dsbt.ci=true -Djava.util.logging.config.file=./logging.properties
  env:
    AZURE_PAT: $(azurePat)
  workingDirectory: $(Agent.BuildDirectory)/project
  condition: or(failed(), succeeded())
  displayName: 'try to publish sample to azure artifacts, this time it works :exploding_head:'

